provisioning script updated

diff --git a/provisioning_lists/baremetal b/provisioning_lists/baremetal
--- a/provisioning_lists/baremetal
+++ b/provisioning_lists/baremetal
@@ -1,11 +1,13 @@
-# platform_type is Baremetal
+### Platform_type is Baremetal
 
-egrep '(vmx|svm)' /proc/cpuinfo
-##   Error: Required VT-X. Please check the BIOS or check the other machine.
+## Check Virtualization on machine
+egrep '(vmx|svm)' /proc/cpuinfo | false && echo 'Error: Required Virtualization. Please check the BIOS or check the other machine.' && exit 1
 
-echo 'options kvm_intel nested=1' >> /etc/modprobe.d/kvm-nested.conf
-modprobe -r kvm_intel && modprobe kvm_intel
-##   Error: Required apply of modprobe command.
+## Modify configuration if the machine can runs for Hypervisor
+echo 'options kvm_intel nested=1' >> /etc/modprobe.d/kvm-nested.conf && modprobe -r kvm_intel && modprobe kvm_intel | false && echo 'Error: Required apply of modprobe command.' && exit 1
 
-cat /sys/module/kvm_intel/parameters/nested
-##   Error: Required check for this file - /sys/module/kvm_intel/parameters/nested for \"Y\"
+## Check the configuration setup success
+cat /sys/module/kvm_intel/parameters/nested | grep "Y" | false && echo "Error: Required check for this file - /sys/module/kvm_intel/parameters/nested for \"Y\"" && exit 1
+
+
+
